spring:
  application:
    name: DBterm_Back

  datasource:
    url: jdbc:postgresql://localhost:5433/dbterm
    username: termadmin
    password: test1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
